// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace GalaxyProtector
{
public static class GPGSIds
{
        public const string achievement_20_enemy_ships_destroyed = "CgkI6fq2k60YEAIQBQ"; // <GPGSID>
        public const string leaderboard_galaxy_protectors_leaderboard = "CgkI6fq2k60YEAIQAA"; // <GPGSID>
        public const string achievement_50_enemy_ships_destroyed = "CgkI6fq2k60YEAIQCA"; // <GPGSID>
        public const string package_name = "tk.CrownClownStudios.GalaxyProtectors"; // <GPGSID>
        public const string achievement_10_enemy_ships_destroyed = "CgkI6fq2k60YEAIQBA"; // <GPGSID>
        public const string achievement_40_enemy_ships_destroyed = "CgkI6fq2k60YEAIQBw"; // <GPGSID>
        public const string achievement_30_enemy_ships_destroyed = "CgkI6fq2k60YEAIQBg"; // <GPGSID>

}
}
